[package]
name = "passage_flex"
version = "0.1.0"
edition = "2021"

[dependencies]
openapi = { path = "./openapi" }
reqwest = { version = "^0.12", features = ["json", "multipart"] }
serde_json = "^1.0"
http = "^1.1.0"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
mockito = "1.5.0"
