/*
 * Passage Management API
 *
 * Passage's management API to manage your Passage apps and users.
 *
 * The version of the OpenAPI document: 1
 * Contact: support@passage.id
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppResponse {
    #[serde(rename = "app")]
    pub app: Box<models::AppInfo>,
}

impl AppResponse {
    pub fn new(app: models::AppInfo) -> AppResponse {
        AppResponse {
            app: Box::new(app),
        }
    }
}

