/*
 * Passage Management API
 *
 * Passage's management API to manage your Passage apps and users.
 *
 * The version of the OpenAPI document: 1
 * Contact: support@passage.id
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Layouts {
    #[serde(rename = "profile")]
    pub profile: Vec<models::LayoutConfig>,
    #[serde(rename = "registration")]
    pub registration: Vec<models::LayoutConfig>,
}

impl Layouts {
    pub fn new(profile: Vec<models::LayoutConfig>, registration: Vec<models::LayoutConfig>) -> Layouts {
        Layouts {
            profile,
            registration,
        }
    }
}

