/*
 * Passage Management API
 *
 * Passage's management API to manage your Passage apps and users.
 *
 * The version of the OpenAPI document: 1
 * Contact: support@passage.id
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Model400Error {
    #[serde(rename = "code")]
    pub code: Code,
    #[serde(rename = "error")]
    pub error: String,
}

impl Model400Error {
    pub fn new(code: Code, error: String) -> Model400Error {
        Model400Error { code, error }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Code {
    #[serde(rename = "invalid_request")]
    InvalidRequest,
    #[serde(rename = "custom_provider_required")]
    CustomProviderRequired,
}

impl Default for Code {
    fn default() -> Code {
        Self::InvalidRequest
    }
}
