/*
 * Passage Management API
 *
 * Passage's management API to manage your Passage apps and users.
 *
 * The version of the OpenAPI document: 1
 * Contact: support@passage.id
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserResponse {
    #[serde(rename = "user")]
    pub user: Box<models::UserInfo>,
}

impl UserResponse {
    pub fn new(user: models::UserInfo) -> UserResponse {
        UserResponse {
            user: Box::new(user),
        }
    }
}
