/*
 * Passage Management API
 *
 * Passage's management API to manage your Passage apps and users.
 *
 * The version of the OpenAPI document: 1
 * Contact: support@passage.id
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// AuthMethods : Denotes what methods this app is allowed to use for authentication with configurations
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthMethods {
    #[serde(rename = "passkeys")]
    pub passkeys: Box<models::PasskeysAuthMethod>,
    #[serde(rename = "otp")]
    pub otp: Box<models::OtpAuthMethod>,
    #[serde(rename = "magic_link")]
    pub magic_link: Box<models::MagicLinkAuthMethod>,
}
