/*
 * Passage Management API
 *
 * Passage's management API to manage your Passage apps and users.
 *
 * The version of the OpenAPI document: 1
 * Contact: support@passage.id
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateTransactionRegisterRequest {
    /// the user's unique identifier
    #[serde(rename = "external_id")]
    pub external_id: String,
    /// the immutable display name of the passkey that the user will see
    #[serde(rename = "passkey_display_name")]
    pub passkey_display_name: String,
}


