/*
 * Passage Management API
 *
 * Passage's management API to manage your Passage apps and users.
 *
 * The version of the OpenAPI document: 1
 * Contact: support@passage.id
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Model409Error {
    #[serde(rename = "code")]
    pub code: Code,
    #[serde(rename = "error")]
    pub error: String,
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Code {
    #[serde(rename = "user_already_admin")]
    UserAlreadyAdmin,
    #[serde(rename = "user_already_organization_member")]
    UserAlreadyOrganizationMember,
    #[serde(rename = "user_has_no_passkeys")]
    UserHasNoPasskeys,
    #[serde(rename = "native_client_already_exists")]
    NativeClientAlreadyExists,
    #[serde(rename = "failed_to_sync_email_preferences")]
    FailedToSyncEmailPreferences,
}


