/*
 * Passage Management API
 *
 * Passage's management API to manage your Passage apps and users.
 *
 * The version of the OpenAPI document: 1
 * Contact: support@passage.id
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Model404Error {
    #[serde(rename = "code")]
    pub code: Code,
    #[serde(rename = "error")]
    pub error: String,
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Code {
    #[serde(rename = "admin_not_found")]
    AdminNotFound,
    #[serde(rename = "api_key_not_found")]
    ApiKeyNotFound,
    #[serde(rename = "app_not_found")]
    AppNotFound,
    #[serde(rename = "device_not_found")]
    DeviceNotFound,
    #[serde(rename = "domain_not_found")]
    DomainNotFound,
    #[serde(rename = "email_provider_not_found")]
    EmailProviderNotFound,
    #[serde(rename = "email_template_not_found")]
    EmailTemplateNotFound,
    #[serde(rename = "event_not_found")]
    EventNotFound,
    #[serde(rename = "function_not_found")]
    FunctionNotFound,
    #[serde(rename = "function_secret_key_not_found")]
    FunctionSecretKeyNotFound,
    #[serde(rename = "function_version_not_found")]
    FunctionVersionNotFound,
    #[serde(rename = "metadata_field_not_found")]
    MetadataFieldNotFound,
    #[serde(rename = "oauth2_app_not_found")]
    Oauth2AppNotFound,
    #[serde(rename = "organization_member_not_found")]
    OrganizationMemberNotFound,
    #[serde(rename = "sms_provider_not_found")]
    SmsProviderNotFound,
    #[serde(rename = "sms_template_not_found")]
    SmsTemplateNotFound,
    #[serde(rename = "social_connection_not_found")]
    SocialConnectionNotFound,
    #[serde(rename = "user_not_found")]
    UserNotFound,
    #[serde(rename = "native_client_not_found")]
    NativeClientNotFound,
}


