/*
 * Passage Management API
 *
 * Passage's management API to manage your Passage apps and users.
 *
 * The version of the OpenAPI document: 1
 * Contact: support@passage.id
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaginatedLinks {
    #[serde(rename = "first")]
    pub first: Box<models::Link>,
    #[serde(rename = "last")]
    pub last: Box<models::Link>,
    #[serde(rename = "next")]
    pub next: Box<models::Link>,
    #[serde(rename = "previous")]
    pub previous: Box<models::Link>,
    #[serde(rename = "self")]
    pub param_self: Box<models::Link>,
}


