/*
 * Passage Management API
 *
 * Passage's management API to manage your Passage apps and users.
 *
 * The version of the OpenAPI document: 1
 * Contact: support@passage.id
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SocialConnectionType {
    #[serde(rename = "apple")]
    Apple,
    #[serde(rename = "github")]
    Github,
    #[serde(rename = "google")]
    Google,

}

impl std::fmt::Display for SocialConnectionType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Apple => write!(f, "apple"),
            Self::Github => write!(f, "github"),
            Self::Google => write!(f, "google"),
        }
    }
}


