/*
 * Passage Management API
 *
 * Passage's management API to manage your Passage apps and users.
 *
 * The version of the OpenAPI document: 1
 * Contact: support@passage.id
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UserEventAction {
    #[serde(rename = "register")]
    Register,
    #[serde(rename = "login")]
    Login,
    #[serde(rename = "other")]
    Other,

}

impl std::fmt::Display for UserEventAction {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Register => write!(f, "register"),
            Self::Login => write!(f, "login"),
            Self::Other => write!(f, "other"),
        }
    }
}


