name: Publish to crate.io

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  run-test-workflow:
    uses: ./.github/workflows/on-pull-request.yml
  
  publish:
    name: Publish to crate.io
    needs: run-test-workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  tag-and-release:
    name: Tag and Release
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get version
        id: get_version
        run: echo "version=$(cat Cargo.toml | grep version | head -n1 | cut -d '"' -f2)" >> "$GITHUB_OUTPUT"

      - uses: rickstaa/action-create-tag@v1
        id: tag_create
        with:
          tag: v${{ steps.get_version.outputs.version }}

      - name: Create Release
        if: !steps.tag_create.outputs.tag_exists
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: v${{ steps.get_version.outputs.version }}
