name: Publish to crate.io

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  run-test-workflow:
    uses: ./.github/workflows/on-pull-request.yml
  
  publish:
    name: Publish to crate.io
    needs: run-test-workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  tag-and-release:
    name: Tag and Release
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get version
        run: echo "VERSION=$(cat Cargo.toml | grep version | head -n1 | cut -d '"' -f2)" >> "$GITHUB_ENV"

      - uses: rickstaa/action-create-tag@v1
        id: tag_create
        with:
          tag: v${{ env.VERSION }}

      - name: Check if release is needed
        id: check
        run: |
          last_version=$(git describe --tags --abbrev=0)
          if [[ "$VERSION" == "$last_version" ]]; then
            # no release needed
            echo "create_release=false" >> "$GITHUB_OUTPUT"
          else
            echo "create_release=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Create Release
        if: steps.check.outputs.create_release == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: v${{ env.VERSION }}
