name: Yank a published version from crate.io

on:
    workflow_dispatch:
      inputs:
        version:
          description: The version number you wish to yank from crate.io
          required: true
          type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  yank:
    name: Yank a published version from crate.io
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - name: Yank
        if: github.event.inputs.version != ''
        run: cargo yank ${{ github.event.inputs.version }} --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
